language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libeigen3-dev
    - build-essential
    - gcc-6
    - g++-6

before_install:
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 60
- g++ -v

script:
- mkdir build && cd build
- cmake ..
- make

compiler:
- g++
- clang
