language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - h-rayflood/llvm
    packages:
    - libeigen3-dev
    - build-essential
    - g++-6
    - clang

before_install:
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
- gcc -v

script:
- mkdir build && cd build
- cmake ..
- make

compiler:
- gcc
- clang
