language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - sourceline: 'george-edison55/precise-backports'
          packages:
          - g++-5
          - cmake
      env: COMPILER=g++-5
    - compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - sourceline: 'george-edison55/precise-backports'
          packages:
          - g++-6
          - cmake
      env: COMPILER=g++-6
    - compiler: clang
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.6
          - sourceline: 'george-edison55/precise-backports'
          packages:
          - clang-3.6
          - cmake
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.9
          - sourceline: 'george-edison55/precise-backports'
          packages:
          - clang-3.9
          - cmake
      env: COMPILER=clang++-3.9

script:
- cmake --version
- mkdir build && cd build
- cmake -DCMAKE_CXX_COMPILER=$COMPILER ..
- make
- ./testing
